permalink: /:basename/
title: High-Demand Digital Asset Showcase | Sean August Horvath 
description: Highly-polished collection of in-demand digital products illustrating technical & creative abilities in a more intentional way than typical portfolios. 
baseurl: "/"
url: "https://design.august.style/"
collections:
  pages:
    output: true
    permalink: /:basename/